gsb_homepage:
    path:   /index
    defaults: { _controller: AheGsbBundle:Default:index }
gsb_homepage_visiteurs:
    path:   /indexV
    defaults: { _controller: AheGsbBundle:FraisVisiteurs:accueilVisiteurs }
gsb_saisie_frais:
    path: /saisieFrais
    defaults: { _controller: AheGsbBundle:FraisVisiteurs:saisirFraisForfait }
gsb_valide_frais:
    path: /valideFrais
    defaults: { _controller: AheGsbBundle:FraisVisiteurs:validerFraisForfait }
gsb_consultation_frais:
    path: /consultationFrais
    defaults: { _controller: AheGsbBundle:FraisVisiteurs:consulterFraisForfait }
gsb_consultation_Frais_Mois:
    path: /listeFraisForfait
    defaults: { _controller: AheGsbBundle:FraisVisiteurs:listerFraisForfait }
gsb_visiteurs_deconnexion:
    path: /deconnexion
    defaults: { _controller: AheGsbBundle:Default:seDeconnecter }
    
gsb_homepage_comptable:
    path: /indexC
    defaults: { _controller: AheGsbBundle:Comptable:accueilComptable }
gsb_comptable_deconnexion:
    path: /deconnexion
    defaults: { _controller: AheGsbBundle:Default:seDeconnecter }